# Generated by Django 2.0.7 on 2018-11-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment_type', models.CharField(blank=True, max_length=30)),
                ('Assessment_Date', models.DateField()),
                ('Assessment_Brief', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Behavior_Title', models.CharField(blank=True, max_length=30)),
                ('Behavior_Function', models.CharField(blank=True, choices=[('SA', 'Social Attention'), ('TA', 'Tangibles or Activities'), ('EA', 'Escape or Avoidance'), ('SS', 'Sensory Stimulation')], max_length=2)),
                ('Behavior_Antecedent', models.CharField(blank=True, max_length=30)),
                ('Behavior_Consequence', models.CharField(blank=True, max_length=30)),
                ('Behavior_Description', models.TextField(blank=True)),
                ('Behavior_HarmToSelf', models.BooleanField(default=True)),
                ('Behavior_HarmToSelfTypePhysical', models.CharField(blank=True, choices=[('Threatening', 'Threatening'), ('Name calling', 'Name calling'), ('Ordering', 'Ordering'), ('Denial', 'Denial'), ('Abusive anger', 'Abusive anger')], max_length=10)),
                ('Behavior_HarmToOthers', models.BooleanField(default=True)),
                ('Behavior_HarmToOthersTypePhysical', models.CharField(blank=True, choices=[('Threatening', 'Threatening'), ('Name calling', 'Name calling'), ('Ordering', 'Ordering'), ('Denial', 'Denial'), ('Abusive anger', 'Abusive anger')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_FirstName', models.CharField(blank=True, max_length=30)),
                ('Client_LastName', models.CharField(blank=True, max_length=30)),
                ('Client_DOB', models.DateField()),
                ('Client_Gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
                ('Client_ServiceProvider', models.CharField(blank=True, max_length=30)),
                ('Client_AdditionalServiceProvider', models.CharField(blank=True, max_length=30)),
                ('Client_CommunicationStyle', models.CharField(blank=True, choices=[('NV', 'Non-verbal'), ('V', 'Verbal')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dislikes_Name', models.CharField(blank=True, max_length=30)),
                ('Dislike_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyMember_FirstName', models.CharField(blank=True, max_length=30)),
                ('FamilyMember_LastName', models.CharField(blank=True, max_length=30)),
                ('FamilyMember_Relationship', models.CharField(blank=True, choices=[('mother', 'Mum'), ('father', 'Dad'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('auntie', 'Auntie'), ('nephew', 'Nephew'), ('son', 'Son'), ('daughter', 'Daughter')], max_length=30)),
                ('FamilyMember_ContactNumber', models.IntegerField(blank=True)),
                ('FamilyMember_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_FirstName', models.CharField(blank=True, max_length=30)),
                ('Friend_LastName', models.CharField(blank=True, max_length=30)),
                ('Friend_ContactNumber', models.IntegerField(blank=True)),
                ('Friend_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthcareProfessional_FirstName', models.CharField(blank=True, max_length=30)),
                ('HealthcareProfessional_LastName', models.CharField(blank=True, max_length=30)),
                ('HealthcareProfessional_ContactNumber', models.IntegerField(blank=True)),
                ('HealthcareProfessional_Profession', models.CharField(blank=True, max_length=30)),
                ('HealthcareProfessional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbie_Name', models.CharField(blank=True, max_length=30)),
                ('Hobbie_frequency', models.IntegerField(blank=True)),
                ('Hobbie_location', models.CharField(blank=True, max_length=30)),
                ('Hobbie_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='HouseMates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseMates_FirstName', models.CharField(blank=True, max_length=30)),
                ('HouseMates_LastName', models.CharField(blank=True, max_length=30)),
                ('HouseMates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes_Name', models.CharField(blank=True, max_length=30)),
                ('Like_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client')),
            ],
        ),
        migrations.AddField(
            model_name='behavior',
            name='Behavior_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Client'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Assessment_Assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.HealthcareProfessional'),
        ),
    ]
