# Generated by Django 2.0.7 on 2018-11-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='Assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assessment', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='Behavior_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Behavior', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='Dislike_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dislike', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='FamilyMember_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FamilyMember', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='Friend_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='HealthcareProfessional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HealthcareProfessional', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='hobbie',
            name='Hobbie_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hobbie', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='housemates',
            name='HouseMates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HouseMates', to='cms.Client'),
        ),
        migrations.AlterField(
            model_name='like',
            name='Like_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='cms.Client'),
        ),
    ]
