# Generated by Django 2.0.7 on 2018-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20181119_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbatool',
            name='Assessment_Setting',
            field=models.CharField(blank=True, choices=[('Is in the community', 'Is in the community'), ('Has recently been disciplined', 'Has recently been disciplined'), ('Is engaged in an activity or task they dislike', 'Is engaged in an activity or task they dislike')], max_length=30),
        ),
    ]
