# Generated by Django 2.0.7 on 2018-11-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181119_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment',
            new_name='FBATool',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Antecedent',
            new_name='FBATool_Antecedent',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Behaviour',
            new_name='FBATool_Behaviour',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Brief',
            new_name='FBATool_Brief',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Consequence',
            new_name='FBATool_Consequence',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Date',
            new_name='FBATool_Date',
        ),
        migrations.RenameField(
            model_name='fbatool',
            old_name='Assessment_Title',
            new_name='FBATool_Function',
        ),
        migrations.RemoveField(
            model_name='fbatool',
            name='Assessment_Setting',
        ),
        migrations.AddField(
            model_name='fbatool',
            name='FBATool_Setting',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fbatool',
            name='FBATool_Title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
